services:
  stockservice.api:
    image: stockservice.api
    build:
      context: .
      dockerfile: src/StockService/StockService.Api/Dockerfile.dev
    ports:
      - "5001:5000"
    environment:
      - ConnectionStrings__DefaultConnection=${STOCK_DEFAULT_CONNECTION}
      - Cors__PolicyName=${STOCK_CORS_POLICYNAME}
      - Cors__Origins=${STOCK_CORS_ORIGINS}
      - RabbitMqSettings__ConnectionString=rabbitmq://rabbitmq:5672
      - RabbitMqSettings__User=${RABBITMQ_USER}
      - RabbitMqSettings__Password=${RABBITMQ_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src:/app/src
    depends_on:
      stockservice.db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  stockservice.db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${STOCK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${STOCK_POSTGRES_PASSWORD}
      POSTGRES_DB: ${STOCK_POSTGRES_DB}
    ports:
      - "${STOCK_POSTGRES_PORT}:5432"
    volumes:
      - stockpgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${STOCK_POSTGRES_USER} -d ${STOCK_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  invoiceservice.api:
    image: invoiceservice.api
    build:
      context: .
      dockerfile: src/InvoiceService/InvoiceService.Api/Dockerfile.dev
    ports:
      - "5002:5000"
    environment:
      - ConnectionStrings__DefaultConnection=${INVOICE_DEFAULT_CONNECTION}
      - Cors__PolicyName=${INVOICE_CORS_POLICYNAME}
      - Cors__Origins=${INVOICE_CORS_ORIGINS}
      - RabbitMqSettings__ConnectionString=rabbitmq://rabbitmq:5672
      - RabbitMqSettings__User=${RABBITMQ_USER}
      - RabbitMqSettings__Password=${RABBITMQ_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src:/app/src
    depends_on:
      invoiceservice.db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  invoiceservice.db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${INVOICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${INVOICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${INVOICE_POSTGRES_DB}
    ports:
      - "${INVOICE_POSTGRES_PORT}:5432"
    volumes:
      - invoicepgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${INVOICE_POSTGRES_USER} -d ${INVOICE_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway.api:
    image: gateway.api
    build:
      context: .
      dockerfile: src/Gateway/Gateway.Api/Dockerfile.dev
    ports:
      - "5005:5000"
    environment:
      - Cors__PolicyName=${GATEWAY_CORS_POLICYNAME}
      - Cors__Origins=${GATEWAY_CORS_ORIGINS}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      invoiceservice.api:
        condition: service_started
      stockservice.api:
        condition: service_started
      customerservice.api:
        condition: service_started
    volumes:
      - ./src:/app/src

  customerservice.api:
    image: customerservice.api
    build:
      context: .
      dockerfile: src/CustomerService/CustomerService.Api/Dockerfile.dev
    ports:
      - "5003:5000"
    environment:
      - ConnectionStrings__DefaultConnection=${CUSTOMER_DEFAULT_CONNECTION}
      - Cors__PolicyName=${CUSTOMER_CORS_POLICYNAME}
      - Cors__Origins=${CUSTOMER_CORS_ORIGINS}
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src:/app/src
    depends_on:
      customerservice.db:
        condition: service_healthy

  customerservice.db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${CUSTOMER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CUSTOMER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CUSTOMER_POSTGRES_DB}
    ports:
      - "${CUSTOMER_POSTGRES_PORT}:5432"
    volumes:
      - customerpgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CUSTOMER_POSTGRES_USER} -d ${CUSTOMER_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      retries: 5
      timeout: 5s
      
  angular.app:
    image: angular.app
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: [ "npm", "run", "start" ]
    depends_on:
      gateway.api:
        condition: service_started


volumes:
  stockpgdata:
  rabbitmqdata:
  invoicepgdata:
  customerpgdata:
