FROM mcr.microsoft.com/dotnet/sdk:9.0 AS dev
WORKDIR /app

COPY ["src/AuthService/AuthService.Api/AuthService.Api.csproj", "src/AuthService/AuthService.Api/"]
COPY ["src/SharedService/SharedService.Shared/SharedService.Shared.csproj", "src/SharedService/SharedService.Shared/"]
COPY ["src/AuthService/AuthService.Application/AuthService.Application.csproj", "src/AuthService/AuthService.Application/"]
COPY ["src/AuthService/AuthService.Domain/AuthService.Domain.csproj", "src/AuthService/AuthService.Domain/"]
COPY ["src/AuthService/AuthService.Infrastructure/AuthService.Infrastructure.csproj", "src/AuthService/AuthService.Infrastructure/"]

RUN dotnet restore "src/AuthService/AuthService.Api/AuthService.Api.csproj"

COPY . .

WORKDIR "/app/src/AuthService/AuthService.Api"

RUN dotnet build "AuthService.Api.csproj" -c Debug

EXPOSE 5000

ENTRYPOINT ["dotnet", "run", "--urls", "http://0.0.0.0:5000"]

